spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: plugin
  base-url: https://2f63bbb9.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG
